[project]
name = "botocoredep"
version = "0.1.0"
requires-python = ">=3.8"
dependencies = [
    "botocore @ git+https://github.com/pcjedi/botocore",
]

[project.optional-dependencies]
test = [
    "pytest>=8.3.4",
]
