[project]
name = "boto3dep"
version = "0.1.0"
requires-python = ">=3.8"
dependencies = [
    "boto3 >= 1.35.99",
    "botocore @ git+https://github.com/pcjedi/botocore@develop",
]

[project.optional-dependencies]
test = [
    "pytest>=8.3.4",
]
