[project]
name = "boto3dep"
version = "0.1.0"
requires-python = ">=3.8"
dependencies = [
    "boto3 >= 1.34.131",
    "cachetools >= 5"
]

[project.optional-dependencies]
test = [
    "pytest>=8.3.4",
]
