on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        uv-resolution: ["highest", "lowest"]
    steps:
      - uses: actions/checkout@v4.2.2
      - run: pipx install uv
      - run: uv pip install .
        env:
          UV_RESOLUTION: ${{ matrix.uv-resolution }}
      - run: uv run python -m doctest -v src/boto3dep/__init__.py
