on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        uv-resolution: ["highest", "lowest"]
    env:
      UV_RESOLUTION: ${{ matrix.uv-resolution }}
      UV_SYSTEM_PYTHON: true
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-python@v5.3.0
        with:
          python-version: "3.10"
      - run: pipx install uv
      - run: uv pip install .
      - run: uv pip install '.[test]'
      - run: pytest src/boto3dep/__init__.py  --doctest-modules
