on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        uv-resolution: ["highest", "lowest"]
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-python@v5.3.0
        with:
          python-version: "3.10"
      - run: pipx install uv
      - run: uv venv
      - run: uv pip install .[test]
        env:
          UV_RESOLUTION: ${{ matrix.uv-resolution }}
      - run: uv run python -m doctest -v src/boto3dep/__init__.py
      - run: uv run pytest src/boto3dep/__init__.py  --doctest-modules
